

{

"wallpaper":"http://www.kf666888.cn/api/tvbox/img",
"spider":"https://codeberg.org/xxpctv/qmleyuandyingxiqu/raw/branch/master/listings/qnzm.html;md5;E4D6649A806929AA2CF6EA7E490A8D18",

"lives":[{"group":"redirect","channels":[{"name":"redirect","urls":["proxy://do=live&type=txt&ext=aHR0cHM6Ly9hZ2l0LmFpL3h4cGN0di9kaXkvcmF3L2JyYW5jaC9tYXN0ZXIvdGVzdC9kcy50eHQ="]}]}],

"sites":[
{"key":"t4public","name":"T4公共💳","type":4,"api":"https://t4.secan.icu/vod?sites=all&ali_token=3781469b13074e4cac1e0e7113e4fa20&timeout=10","searchable":1,"quickSearch":1,"filterable":0},
{"key": "T4","name": "豆瓣荐片🐞","type": 4,"api": "https://t4.secan.icu/vod?sites=all&timeout=7","searchable": 1,"quickSearch": 1,"filterable": 1},
{"key":"csp_Kunyu77","name":"七七🐞","type":3,"api":"csp_Kunyu77","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Kuaikan","name":"快看🐞","type":3,"api":"csp_Kuaikan","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Cokemv","name":"Cokemv🐞","type":3,"api":"csp_Cokemv","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_SP360","name":"️360🎾","api":"csp_SP360","type":3,"filterable":1,"quickSearch":1,"searchable":1},
{"key": "棋牌","name": "棋牌🅱️","type": 3,"api": "csp_Bili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/diy/raw/branch/master/xbiubiu/%e6%a3%8b%e7%89%8c0806.json","jar":"https://agit.ai/xxpctv/diy/raw/branch/master/ceshi/Bili0825.html;md5;C5C337BB2793598E9AA5953898FBB087"},


{"key":"csp_XYQBiu_17看","name":"一起看🏀","type":3,"api":"csp_XYQBiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/17.py"},
{"key":"csp_xpath_qiumi","name": "球迷🏀","type": 3,"api": "csp_XPathFilter","searchable": 1,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/sszb.py"},
{"key":"csp_xpath_88kanqiu","name": "看球吧⚽","type": 3,"api": "csp_XPathMac","searchable": 1,"quickSearch": 0,"filterable": 0,"ext": "https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/kq88.py"},
{"key":"csp_XYQBiu_310直播","name":"三一零⚽","type":3,"api":"csp_XYQBiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/310.py"},
{"key":"DJ-XP-低调看","name":"低调看🏀","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/ddk.py"},
{"key":"DJ-XP-优直播","name":"优直播🏀","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/yzb.py"},
{"key":"DJ-XP-零点吧","name":"零点吧🏀","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/nzhiban/raw/branch/master/ziyong/ldb.py"},
{"key":"csp_xBPQ_zhi","name":"️抓饭体育🎾","type":3,"api":"csp_xBPQ","searchable":1,"quickSearch":1,"filterable":0,"ext":"{\"分类url\":\"https://www.zhuafan.tech/sports-home/category/{cateId}\",\"分类\":\"全部$/all#足球$Football#篮球$Basketball#羽乒$Badminton#台球$Billiards#棒球$Baseball#户外$Outdoors#搏击$Wrestling#综合$Others#棋盘$Boardgame#电竞$Popular#网球$Tennis#排球$Volleyball#聊天$Chat#原声$Acoustic\",\"热门推荐\":\"1\",\"起始页\":\"1\",\"直接播放\":\"1\",\"数组\":\"{&&}\",\"图片\":\"imageUrl\\\":\\\"&&\\\"\",\"标题\":\"cname\\\":\\\"&&\\\"\",\"链接\":\"id\\\":\\\"&&\\\"\",\"链接前缀\":\"https://www.zhuafan.tech/\"}","jar":"https://agit.ai/xxpctv/diy/raw/branch/master/test/762py.html;md5;3E92F56BD34DBC49F26EBCE77B845255"},
{"key": "py_jrk","name": "🌩体育直播jr","type": 3,"api": "py_jrk","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/guozu616/TVbox/raw/branch/main/py/py_jrk.py"}, 
{"key": "py_yytv","name": "🌩体育直播yy","type": 3,"api": "py_yytv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/guozu616/TVbox/raw/branch/main/py/py_yytv.py"}, 
{"key": "py_qie","name": "🌩企鹅体育qe","type": 3,"api": "py_qie","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/guozu616/TVbox/raw/branch/main/py/py_qie.py"},
{"key": "py_jrskbs","name": "🌩体育直播kb","type": 3,"api": "py_jrskbs","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/138001380000/MHQTV/raw/branch/master/py/py_jrskbs.py"}, 
{"key": "py_freezb","name": "🌩球皇直播fr","type": 3,"api": "py_freezb","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/138001380000/MHQTV/raw/branch/master/py/py_freezb.py"}, 


{"key":"csp_QQ","name":"腾（SP官解）","type":3,"api":"csp_QQ","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_MGTV","name":"芒（SP官解）","type":3,"api":"csp_MGTV","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_IQIYI","name":"爱（SP官解）","type":3,"api":"csp_IQIYI","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Czsapp","name": "厂长(SP)","type": 3,"api": "csp_Czsapp","searchable": 1,"quickSearch": 1,"filterable": 1},
{"key":"csp_Auete","name":"Auete（SP）","type":3,"api":"csp_Auete","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_EEEDY","name":"3EDY(SP)","type":3,"api":"csp_EEEDY","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Lezhu","name":"乐猪影视（SP）","api":"csp_Lezhu","type":3,"filterable":1,"quickSearch":1,"searchable":1,"ext":""},
{"key":"csp_Smdyy","name":"神马影院（SP）","type":3,"api":"csp_Smdyy","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Bttoo","name":"两个BT（SP）","type":3,"api":"csp_Bttoo","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Lib","name":"LibVio（SP）","type":3,"api":"csp_Lib","searchable":1,"quickSearch":1,"filterable":0},
{"key":"csp_Mjxq","name":"美剧星球（SP）","type":3,"api":"csp_Mjxq","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_KanSJ","name":"看视界（SP）","api":"csp_KanSJ","type":3,"filterable":1,"quickSearch":1,"searchable":1,"ext":""},
{"key":"csp_Xxys","name":"小熊TV（SP）","type":3,"api":"csp_Xxys","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Anime1","name":"小日本动漫（SP）","type":3,"api":"csp_Anime1","searchable":1,"quickSearch":1,"filterable":1},
{"key": "Bili_哔哩","name": "哔哩（B站）","type": 3,"api": "csp_Bili","searchable":0,"quickSearch": 0,"filterable": 1,"ext": "https://gitee.com/dongji2/tb/raw/master/bi/bbl.json"},
{"key": "Bili_UP主","name": "UP主（B站）","type": 3,"api": "csp_Bili","searchable":0,"quickSearch": 0,"filterable": 1,"ext": "https://gitee.com/dongji2/tb/raw/master/bi/bup.json"},
{"key": "Bili_儿童","name": "儿童（B站）","type": 3,"api": "csp_Bili","searchable":0,"quickSearch": 0,"filterable": 1,"ext": "https://gitee.com/dongji2/tb/raw/master/bi/bertong.json"},
{"key": "Bili_音乐","name": "音乐（B站）","type": 3,"api": "csp_Bili","searchable":0,"quickSearch": 0,"filterable": 1,"ext": "https://gitee.com/dongji2/tb/raw/master/bi/yy.json"},
{"key":"csp_Yj1211","name":"直播（SP）","type":3,"api":"csp_Yj1211","searchable":1,"quickSearch":1,"filterable":1},
{"key": "csp_xBPQ_极品","name": "🍂极品影视(XBPQ)","type": 3,"api": "csp_xBPQ","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/xBPQ/jpys.json","jar":"https://codeberg.org/xxpctv/qmleyuandyingxiqu/raw/branch/master/listings/tn;md5;63F37C0DC42FA60DCC675927B0A9072A"},



{"key":"csp_Alist1","name":"🅿Alist网盘","type":3,"api":"csp_Alist","searchable":0,"quickSearch":0,"filterable":0,"ext":"http://神器每日推送.tk/json/alist.json"},	
{"key":"csp_bendi","name":"🅿本地视频","type":3,"api":"csp_LocalFile","searchable":0,"quickSearch":0,"filterable":0,"type_flag":1},

{"key": "csp_Gitcafe","name": "📜小纸条","type": 3,"api": "csp_Gitcafe","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "59f75b1fda4d4867a9204107a5cc3a6f"},
{"key":"csp_Yiso","name":"易搜","type":3,"api":"csp_Yiso","searchable":1,"quickSearch":1,"filterable":1,"ext":"59f75b1fda4d4867a9204107a5cc3a6f"},
{"key":"csp_AliPanSou","name":"盘搜","type":3,"api":"csp_AliPanSou","searchable":1,"quickSearch":1,"filterable":1,"ext":"59f75b1fda4d4867a9204107a5cc3a6f"},
{"key":"csp_FindZY","name":"找资源","type":3,"api":"csp_FindZY","searchable":1,"quickSearch":1,"filterable":1,"ext":"59f75b1fda4d4867a9204107a5cc3a6f"},
{"key": "csp_PushAgent","name": "🍭推送","type": 3,"api": "csp_PushAgent","searchable": 0,"quickSearch": 0,"filterable": 0,"ext": "59f75b1fda4d4867a9204107a5cc3a6f"},
{"key": "push_agent","name": "🌩阿里","type": 3,"api": "py_ali","searchable": 0,"quickSearch": 0,"filterable": 0,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_ali.py"}, 
{"key": "py_alist","name": "🌩Alist","type": 3,"api": "py_alist","searchable": 0,"quickSearch": 0,"filterable": 0,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_alist.py"}, 
{"key": "py_cctv","name": "🌩央视","type": 3,"api": "py_cctv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_cctv.py"}, 
{"key": "py_cctv_full","name": "🌩央视大全","type": 3,"api": "py_cctv_full","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/diy/raw/branch/master/b2/py_cctv_full.py"},
{"key": "py_czspp","name": "🌩厂长","type": 3,"api": "py_czspp","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_czspp.py"}, 
{"key": "py_zxzj","name": "🌩在线","type": 3,"api": "py_zxzj","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_zxzj.py"}, 
{"key": "py_voflix","name": "🌩Voflix","type": 3,"api": "py_voflix","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_voflix.py"}, 
{"key": "py_gimytv","name": "🌩剧迷","type": 3,"api": "py_gimytv","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_gimytv.py"}, 
{"key": "py_genmov","name": "🌩跟剧","type": 3,"api": "py_genmov","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_genmov.py"},
{"key": "py_cokemv","name": "🌩COKE","type": 3,"api": "py_cokemv","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_cokemv.py"}, 
{"key": "py_xmaomi","name": "🌩猫咪","type": 3,"api": "py_xmaomi","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_xmaomi.py"}, 
{"key": "py_bilimd","name": "🌩B站影视","type": 3,"api": "py_bilimd","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_bilimd.py"}, 
{"key": "py_bilibili","name": "🌩哔哩","type": 3,"api": "py_bilibili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_bilibili.py"}, 
{"key": "py_huya","name": "🌩虎牙","type": 3,"api": "py_huya","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_huya.py"}, 
{"key": "py_douyu","name": "🌩斗鱼","type": 3,"api": "py_douyu","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_douyu.py"}, 
{"key": "py_bilivd","name": "🌩B站","type": 3,"api": "py_bilivd","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_bilivd.py"},
{"key": "py_3qu","name": "🌩3QU","type": 3,"api": "py_3qu","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_3qu.py"},
{"key": "py_cyys","name": "🌩创艺","type": 3,"api": "py_cyys","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_cyys.py"},
{"key": "py_kunyu77","name": "🌩酷云77","type": 3,"api": "py_kunyu77","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_kunyu77"},
{"key": "py_kuaikan","name": "🌩快看","type": 3,"api": "py_kuaikan","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/fenwe/TVBox/raw/branch/master/plugin/py_kuaikan"},
{"key": "py_cctv","name": "🌩央视自选","type": 3,"api": "py_cctv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/diy/raw/branch/master/test/py_cctv.py"},
{"key": "py_douban","name": " 🌩豆瓣","type": 3,"api": "py_douban","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_douban.py"},
{"key": "py_alist","name": " 🌩Alist","type": 3,"api": "py_alist","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_alist.py"},
{"key": " py_bilibili","name": " 🌩哔哩","type": 3,"api": "py_bilibili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_bilibili.py"},
{"key": " py_bilimd","name": " 🌩bili影视","type": 3,"api": "py_bilimd","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_bilimd.py"},
{"key": " py_中医药","name": " 🌩中医药","type": 3,"api": "py_中医药","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_中医药.py"},
{"key": " py_中国文化","name": " 🌩文化","type": 3,"api": "py_中国文化","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_中国文化.py"},
{"key": " py_3qu","name": " 🌩快播","type": 3,"api": "py_3qu","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_3qu.py"},
{"key": " py_kunyu77","name": " 🌩七七","type": 3,"api": "py_kunyu77","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_kunyu77.py"},
{"key":"py_lezhu","name":" 🌩乐猪","type":3,"api":"py_lezhu","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_lezhu.py"},
{"key":"py_star","name":" 🌩星光","type":3,"api":"py_star","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_star.py"},
{"key":"py_cup","name":" 🌩茶杯狐","type":3,"api":"py_cup","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_cup.py"},
{"key": " py_kuaikan","name": " 🌩快看","type": 3,"api": "py_kuaikan","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_kuaikan.py"},	  
{"key": "py_zxzj","name": " 🌩在线","type": 3,"api": "py_zxzj","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_zxzj.py"},
{"key": "py_voflix","name": " 🌩Voflix","type": 3,"api": "py_voflix","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_voflix.py"},
{"key": "py_gimytv","name": " 🌩剧迷","type": 3,"api": "py_gimytv","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_gimytv.py"},
{"key": "py_genmov","name": " 🌩跟剧","type": 3,"api": "py_genmov","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_genmov.py"},
{"key": "py_czspp","name": " 🌩厂长","type": 3,"api": "py_czspp","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_czspp.py"},
{"key": "py_xmaomi","name": " 🌩猫咪","type": 3,"api": "py_xmaomi","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_xmaomi.py"},
{"key": "py_zhaozy","name": " 🌩找资源","type": 3,"api": "py_zhaozy","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_zhaozy.py"},
{"key": "py_pansou","name": " 🌩盘搜","type": 3,"api": "py_pansou","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_pansou.py"},
{"key": "py_yiso","name": " 🌩易搜","type": 3,"api": "py_yiso","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_yiso.py"},   
{"key": "py_gitcafe","name": " 🌩小纸条","type": 3,"api": "py_gitcafe","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_gitcafe.py"},
{"key": "py_cyys","name": "🌩创意","type": 3,"api": "py_cyys","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_cyys.py"},
{"key": "py_push_agent","name": "🌩阿里","type": 3,"api": "py_ali","searchable": 0,"quickSearch": 0,"filterable": 0,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_ali.py"},
{"key": "py_huya","name": "🌩虎牙","type": 3,"api": "py_huya","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_huya.py"},
{"key": "py_douyu","name": "🌩斗鱼","type": 3,"api": "py_douyu","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/gggwang/TVboxo3/raw/branch/main/Py/py_douyu.py"},
{"key" : "py_yixi","name" : "🌩一席话","type" : 3,"api" : "py_yixi","searchable" : 1,"quickSearch" : 1,"filterable" : 1,"ext" : "https://agit.ai/138001380000/MHQTV/raw/branch/master/py/py_yixi.py"},
{"key" : "py_cctvzh","name" : "📺央视综合 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvzh.py"},
{"key" : "py_cctvxw","name" : "📺央视新闻 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvxw.py"},
{"key" : "py_cctvzy","name" : "📺央视综艺 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvzy.py"},
{"key" : "py_cctvdy","name" : "📺央视电影 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvdy.py"},
{"key" : "py_cctvty","name" : "📺央视体育 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvty.py"},
{"key" : "py_cctvfz","name" : "📺央视法治 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctv.py"},
{"key" : "py_cctvkj","name" : "📺央视科教 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvkj.py"},
{"key" : "py_cctvyy","name" : "📺央视音乐 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvyy.py"},
{"key" : "py_cctvse","name" : "📺央视少儿 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvse.py"},
{"key" : "py_cctvny","name" : "📺央视农业 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvny.py"},
{"key" : "py_cctvjs","name" : "📺央视军事 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvjs.py"},
{"key" : "py_cctvxq","name" : "📺央视戏曲 py","type" : 3,"api" : "py_cctv","searchable" : 0,"quickSearch" : 0,"filterable" : 1,"ext" : "https://agit.ai/l/o/raw/branch/o/o/py_cctvxq.py"},

{"key":"dr_TV云播","name":"TV云播🕋(选多多)","type":1,"api":"http://drpy.fuqizhishi.com/vod?rule=TV云播&ext=txt/js/tg/TV云播.js","searchable":2,"quickSearch":0,"filterable":0},
{"key": "dr_真不卡","name": "真不卡🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=真不卡","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_看了么","name": "看了么🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=看了么&ext=txt/js/tg/看了么.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_皮皮泡","name": "皮皮泡🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=皮皮泡&ext=txt/js/tg/皮皮泡.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_大师兄影视","name": "大师兄🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=大师兄影视&ext=txt/js/tg/大师兄影视.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_两个BT","name": "两个BT🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=两个BT&ext=txt/js/tg/两个BT.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_乐猪TV","name": "乐猪TV🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=乐猪TV&ext=txt/js/tg/乐猪TV.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_Nike影视","name": "Nike🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=Nike影视&ext=txt/js/tg/Nike影视.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_MXONE","name": "MXONE🕋","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=MXONE&ext=txt/js/tg/MXONE.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key":"dr_TV云播","name":"TV云播🕋","type":1,"api":"http://drpy.fuqizhishi.com/vod?rule=TV云播&ext=txt/js/tg/TV云播.js","searchable":2,"quickSearch":0,"filterable":0},
{"key": "dr_夜空","name": "夜空🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=夜空","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_360影视","name": "360影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=360影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_追剧喵","name": "追剧喵🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=追剧喵","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_AnFuns","name": "AnFuns🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=AnFuns","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_vip影院","name": "vip影院🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=vip影院","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_喵喵","name": "喵喵🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=喵喵","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_万能影视","name": "万能影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=万能影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_兔小贝","name": "兔小贝🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=兔小贝","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_瓜皮TV","name": "瓜皮TV🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=瓜皮TV","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_奇珍异兽","name": "奇珍异兽🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=奇珍异兽","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_库马伊","name": "库马伊🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=库马伊","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_影视工厂","name": "影视工厂🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=影视工厂","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_干饭影视","name": "干饭影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=干饭影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_腾云驾雾","name": "腾云驾雾🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=腾云驾雾","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_蓝莓影视","name": "蓝莓影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=蓝莓影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_小强迷","name": "小强迷🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=小强迷","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_cokemv","name": "cokemv🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=cokemv","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_蓝光影院","name": "蓝光影院🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=蓝光影院","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_莫扎兔","name": "莫扎兔🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=莫扎兔","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_在线之家","name": "在线之家🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=在线之家","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_看视界","name": "看视界🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=看视界","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_555影视","name": "555影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=555影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_剧白白","name": "剧白白🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=剧白白","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_小猫咪","name": "小猫咪🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=小猫咪","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_l0l","name": "l0l🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=l0l","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_鸭奈飞","name": "鸭奈飞🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=鸭奈飞","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_LIBVIO","name": "LIBVIO🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=LIBVIO","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_1080P","name": "1080P🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=1080P","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_drpy","name": "drpy🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=drpy","searchable": 1,"quickSearch": 1,"filterable": 1},
{"key": "dr_番茄影视","name": "番茄影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=番茄影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_玄天","name": "玄天🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=玄天","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_菜狗","name": "菜狗🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=菜狗","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_人人影视","name": "人人影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=人人影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_007影视","name": "007影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=007影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_凌云影视","name": "凌云影视🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=凌云影视","searchable": 0,"quickSearch": 0,"filterable": 0},
{"key": "dr_大米星球","name": "大米星球🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=大米星球","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_奇优影院","name": "奇优影院🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=奇优影院","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_牛马TV","name": "牛马TV🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=牛马TV","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_酷云77","name": "酷云77🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=酷云77","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_百忙无果","name": "百忙无果🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=百忙无果","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_优酷","name": "优酷🕋","type": 1,"api": "http://www.fenwe.tk:5705/vod?rule=优酷","searchable": 2,"quickSearch": 0,"filterable": 1},


{"key": "DJ-XYQ-看短视频","name":"🍀看短视频（XYQ）","type":3,"api":"csp_XYQBiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tb/raw/master/xyq/分享短视频.json"},
{"key": "DJ-XYQ-大米星球","name":"🍀大米星球（XYQ）","type":3,"api":"csp_XYQBiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tb/raw/master/xyq/大米星球.json"},
{"key": "DJ-XYQ-凌云影视","name":"🍀凌云影视（XYQ）","type": 3,"api":"csp_XYQBiu","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://gitee.com/dongji2/tb/raw/master/xyq/凌云影视.json"},
{"key": "DJ-XYQ-万能影院","name":"🍀万能影院（XYQ）","type": 3,"api":"csp_XYQBiu","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://gitee.com/dongji2/tb/raw/master/xyq/万能影院.json"},


{"key":"DJ-XP-乐猪TV","name":"乐猪TV（XP）","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/mm/raw/master/xp/lezhutv.json"},
{"key":"DJ-XP-两个BT","name":"两个BT（XP）","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/bttwoo.json"},
{"key":"DJ-XP-31看看","name":"31看看（XP）","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/mm/raw/master/xp/31kan.js"},
{"key":"DJ-XP-厂长资源","name":"厂长资源（XP）","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/czspp.json"},
{"key":"DJ-XP-片库资源","name":"片库资源（XP）","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/pianku.json"},
{"key":"DJ-XP-音范丝","name":"音范丝（XP蓝光磁力）","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/yinfans.json"},

{"key":"DJ-XPF-剧白白","name":"剧白白（XPF）","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/mm/raw/master/xp/jubaibai.json"},
{"key":"DJ-XPF-达达龟","name":"达达龟（XPF）","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dadagui.json"},
{"key":"DJ-XPF-六度TV","name":"六度TV（XPF）","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/6d.json"},
{"key":"DJ-XPF-789影吧","name":"789影吧（XPF）","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp.json"},
{"key":"DJ-XPF-在线之家","name":"在线之家（XPF）","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/zxzj2.json"},

{"key":"DJ-XB-双十电影","name":"双十电影（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/双十电影.json"},
{"key":"DJ-XP-SH电影","name":"SH电影（XP）","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/mm/raw/master/xp/saohuo.json"},
{"key":"DJ-XB-瓜皮TV","name":"瓜皮TV（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/瓜皮TV.json"},
{"key":"DJ-XB-蓝光影院","name":"蓝光影院（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/蓝光影院.json"},
{"key":"DJ-XB-555影院","name":"555影院（XB）","type": 3,"api": "csp_XBiubiu","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://gitee.com/dongji2/bb/raw/master/custom/555.json"},
{"key":"DJ-XB-LIBVIO","name":"LIBVIO（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tb/raw/master/xb/libvio.json"},
{"key":"DJ-XB-影视工厂","name":"影视工厂（XB）","type":3,"api":"csp_XBiubiu","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://gitee.com/dongji2/tt/raw/master/collection/xb/影视工厂.json"},

{"key":"DJ-XB-蓝豆影院","name":"蓝豆影院（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/蓝豆TV.json"},
{"key":"DJ-XB-思乐影视","name":"思乐影视（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/思乐影视.json"},
{"key":"DJ-XB-口袋影院","name":"口袋影院（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/口袋影院.json"},
{"key":"DJ-XB-黑洞影视","name":"黑洞影视（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/黑洞影视.json"},
{"key":"DJ-XB-北川影视","name":"北川影视（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/北川影视.json"},
{"key":"DJ-XB-奇粹影院","name":"奇粹影院（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/奇粹影院.json"},
{"key":"DJ-XB-九亿国语","name":"九亿国语（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/9亿资源.json"},
{"key":"DJ-XB-大米星球","name":"大米星球（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/大米星球.json"},
{"key":"DJ-XB-voflix","name":"voflix（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/voflix.json"},
{"key":"DJ-XB-茶杯狐","name":"茶杯狐（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/cupfox.json"},
{"key":"DJ-XB-夜空高清","name":"夜空高清（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/yekong.json"},
{"key":"DJ-XB-奇优影院","name":"奇优影院（XB）","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/qiyou.json"},
{"key":"DJ-XB-蓝莓影视","name":"蓝莓影视（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/lanmei.json"},



{"key":"DJ-XP-huya","name":"🐯虎牙(XP)","type":3,"api":"csp_XPathMacFilter","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/huya2.json"},
{"key":"DJ-XB-斗鱼","name":"🥒斗鱼(XB)","type":3,"api":"csp_XBiubiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/斗鱼.json"},
{"key":"DJ-XP-kuqi","name":"🎤酷奇MV(XP)","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/kuqimv.json"},
{"key":"DJ-XB-听书网","name":"🥒听书网（XB）","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/tingbook.json"},

{"key":"DJ-多多资源","name":"极速⚡","type":1,"api":"https://www.ddzyz1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["国产剧","港台剧","日韩剧","欧美剧","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","犯罪片","悬疑片","动画片","泰国剧","国产动漫","日韩动漫","欧美动漫","惊悚片","奇幻片","冒险片","武侠片","海外剧","国内综艺","海外综艺"]},
{"key":"DJ-1080zyk","name":"1080⚡","type":1,"api":"https://api.1080zyku.com/inc/api_mac10.php","searchable":1,"quickSearch":0,"categories":["国产剧","综艺","动漫","动画片","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","韩国剧","欧美剧","香港剧","泰国剧","日本剧","港台剧"]},



{"key":"csp_xpath_auete","name":"Auete影视(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":0,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/auete.json"},
{"key":"csp_xpath_tvci","name":"大师兄(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/tvci.json"},
{"key":"csp_xpath_meiju56","name":"美剧网(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/meiju562.json"},
{"key":"csp_xpath_ctv","name":"冲TMTV(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/chongtmtv.json"},
{"key":"csp_xpath_cokemv","name":"Cokemv(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/cokemv.json"},
{"key":"csp_xpath_Jumi","name":"剧迷TV(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/Jumi.json"},
{"key":"csp_xpath_唐人街","name":"唐人街(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/Renjie.json"},
{"key":"csp_xpath_lranc","name":"天天影视(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/lranc.json"},
{"key":"csp_xpath_yanetflix","name":"鸭奈飞(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/yanet.json"},
{"key":"csp_xpath_Ole","name":"欧乐(XPF)(播放器要改成Exo)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/olevod.json"},
{"key":"csp_xpath_xxys520","name":"小熊影视(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/xxys520.json"},
{"key":"csp_xpath_348z","name":"348电影(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/348z.json"},
{"key":"csp_xpath_Gimy","name":"GIMY影视(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/Gimy.json"},
{"key":"csp_xpath_Gimy2","name":"GimyTV(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/Gimy2.json"},
{"key":"csp_xpath_naifeiorg","name":"奈飞中文(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/naifeiorg.json"},
{"key":"csp_xpath_ttsp","name":"天天视频(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/ttsp.json"},
{"key":"csp_xpath_789kp","name":"789看片(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/789kp.json"},
{"key":"csp_xpath_dmntv","name":"弹幕影院(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dmntv.json"},
{"key":"csp_xpath_dmw","name":"动漫岛(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dmw.json"},
{"key":"csp_xpath_ysjdm","name":"异世界动漫(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/ysjdm.json"},
{"key":"csp_xpath_dandanzan10","name":"蛋蛋赞(电影)(XPF)","type":3,"api":"csp_XPathFilter","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dandanzan10.json"},
{"key":"csp_xpath_4kpianku","name":"4k片库网(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/4kpianku.json"},
{"key":"csp_xpath_xiangdao","name":"农民影视(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/xiangdao.json"},
{"key":"csp_xpath_lkvod","name":"耐看点播(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/lkvod.json"},
{"key":"csp_xpath_age","name":"AGE动漫(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/agefans.json"},
{"key":"csp_xpath_dm84","name":"动漫巴士(XP)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dm84.json"},
{"key":"csp_xpath_yinghua","name":"樱花动漫(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/yinghua2.json"},
{"key":"csp_xpath_17skr","name":"路漫漫动漫(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/17skr.json"},
{"key":"csp_xpath_wanmeikk","name":"完美看看(XP)","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/wanmeikk.json"},
{"key":"csp_xpath_zaixiandianying8","name":"在线电影(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/zaixiandianying8.json"},
{"key":"csp_xpath_zzzlike","name":"周末电影(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/zzzlike.json"},
{"key":"csp_xpath_135kan","name":"135看看(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/135kan.json"},
{"key":"csp_xpath_xfeiji","name":"小小影视(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/xfeiji.json"},
{"key":"csp_xpath_osx3","name":"达达兔(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/osx3.json"},
{"key":"csp_xpath_dianyingn","name":"电影牛(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dianyingn.json"},
{"key":"csp_xpath_newfii","name":"奈落影院(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/newfii.json"},
{"key":"csp_xpath_dym8","name":"电影迷(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dym8.json"},
{"key":"csp_xpath_xuangz","name":"尘落电影(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/xuangz.json"},
{"key":"csp_xpath_qdytv","name":"米来影视(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/qdytv.json"},
{"key":"csp_xpath_dingzidy","name":"钉子电影(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/dingzidy.json"},
{"key":"csp_xpath_paopaoshipin","name":"泡泡视频(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/paopaoshipin.json"},
{"key":"csp_xpath_rttks","name":"人人影视(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/rttks.json"},
{"key":"csp_xpath_ikan6","name":"爱看影视(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/ikan6.json"},
{"key":"csp_xpath_akmeiju","name":"爱看美剧(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/akmeiju.json"},
{"key":"csp_xpath_hiyszx","name":"影视在线(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/hiyszx.json"},
{"key":"csp_xpath_xqmi","name":"小强迷(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/xqmi.json"},
{"key":"csp_xpath_juhuang","name":"剧荒TV(XPMac)","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/juhuang.json"},
{"key":"csp_xpath_doujiaow","name":"豆角网(XP)","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/doujiaow.json"},
{"key":"csp_xpath_yyotv","name":"小太阳(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/yyotv.json"},
{"key":"csp_xpath_jiujiukanpian","name":"久久影视(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/jiujiukanpian.json"},
{"key":"csp_xpath_pianba","name":"片吧影院(XPMac)","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/pianba.json"},
{"key":"csp_xpath_duboku","name":"独播库(XPMac)","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/duboku2.json"},
{"key":"csp_xpath_zj883","name":"追剧网(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/zj883.json"},
{"key":"csp_xpath_cerrd","name":"真不卡影院(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/cerrd.json"},
{"key":"csp_xpath_so2","name":"淘剧鸭(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xp/so2.json"},
{"key":"csp_biubiu_厂长资源-蓝光","name":"🥒厂长资源(XB)","type":3,"api":"csp_XBiubiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/厂长资源-蓝光.json"},
{"key":"csp_biubiu_Auete影视","name":"🥒Auete影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/Auete影视.json"},
{"key":"csp_biubiu_COKEMV","name":"🥒COKEMV(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/COKEMV.json"},
{"key":"csp_biubiu_555电影","name":"🥒555电影(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/555电影.json"},
{"key":"csp_biubiu_特狗影视","name":"🥒特狗影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/特狗影视.json"},
{"key":"csp_biubiu_F7好看剧","name":"🥒F7好看剧(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/F7好看剧.json"},
{"key":"csp_biubiu_喜鹊视频","name":"🥒喜鹊视频(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/喜鹊视频.json"},
{"key":"csp_biubiu_瓜皮TV","name":"🥒瓜皮TV(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/瓜皮TV.json"},
{"key":"csp_biubiu_看片狂人","name":"🥒看片狂人(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/看片狂人.json"},
{"key":"csp_biubiu_真的卡影院","name":"🥒真的卡影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/真的卡影院.json"},
{"key":"csp_biubiu_荣耀Glory","name":"🥒荣耀Glory(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/荣耀Glory.json"},
{"key":"csp_biubiu_晗剧","name":"🥒晗剧(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/晗剧.json"},
{"key":"csp_biubiu_87影院","name":"🥒87影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/87影院.json"},
{"key":"csp_biubiu_dunkfun","name":"🥒dunkfun(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/dunkfun.json"},
{"key":"csp_biubiu_麻衣高清","name":"🥒麻衣高清(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/麻衣高清.json"},
{"key":"csp_biubiu_干饭影视","name":"🥒干饭影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/干饭影视.json"},
{"key":"csp_biubiu_悟空影视","name":"🥒悟空影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/悟空影视.json"},
{"key":"csp_biubiu_虚拟影院","name":"🥒虚拟影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/虚拟影院.json"},
{"key":"csp_biubiu_OmoFun动漫","name":"🥒OmoFun动漫(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/OmoFun动漫.json"},
{"key":"csp_biubiu_去看吧","name":"🥒去看吧(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/去看吧.json"},
{"key":"csp_biubiu_次元城","name":"🥒次元城(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/次元城.json"},
{"key":"csp_biubiu_风车动漫","name":"🥒风车动漫(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/风车动漫.json"},
{"key":"csp_biubiu_森屋新番","name":"🥒森屋新番(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/森屋新番.json"},
{"key":"csp_biubiu_漫岛动漫","name":"🥒漫岛动漫(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/漫岛动漫.json"},
{"key":"csp_biubiu_打驴动漫","name":"🥒打驴动漫(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/打驴动漫.json"},
{"key":"csp_biubiu_维奇动漫","name":"🥒维奇动漫(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/维奇动漫.json"},
{"key":"csp_biubiu_真不卡影院-不支持搜索","name":"🥒真不卡影院-不支持搜索(XB)","type":3,"api":"csp_XBiubiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/真不卡影院-不支持搜索.json"},
{"key":"csp_biubiu_周末电影","name":"🥒周末电影(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/周末电影.json"},
{"key":"csp_biubiu_神马影视","name":"🥒神马影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/神马影视.json"},
{"key":"csp_biubiu_六度TV","name":"🥒六度TV(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/六度TV.json"},
{"key":"csp_biubiu_348电影网","name":"🥒348电影网(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/348电影网.json"},
{"key":"csp_biubiu_GIMY影视","name":"🥒GIMY影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/GIMY影视.json"},
{"key":"csp_biubiu_GimyTV","name":"🥒GimyTV(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/GimyTV.json"},
{"key":"csp_biubiu_YYDS影院","name":"🥒YYDS影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/YYDS影院.json"},
{"key":"csp_biubiu_开心果电影网","name":"🥒开心果电影网(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/开心果电影网.json"},
{"key":"csp_biubiu_如如影视","name":"🥒如如影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/如如影视.json"},
{"key":"csp_biubiu_VIP电影院","name":"🥒VIP电影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/VIP电影院.json"},
{"key":"csp_biubiu_看一看影视","name":"🥒看一看影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/看一看影视.json"},
{"key":"csp_biubiu_789影视","name":"🥒789影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/789影视.json"},
{"key":"csp_biubiu_人人影视","name":"🥒人人影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/人人影视.json"},

{"key":"csp_biubiu_chok8电影","name":"🥒chok8电影(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/chok8电影.json"},
{"key":"csp_biubiu_九州影视","name":"🥒九州影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/九州影视.json"},
{"key":"csp_biubiu_融兴影视","name":"🥒融兴影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/融兴影视.json"},
{"key":"csp_biubiu_鸭奈飞","name":"🥒鸭奈飞(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/鸭奈飞.json"},
{"key":"csp_biubiu_爱港剧","name":"🥒爱港剧(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/爱港剧.json"},
{"key":"csp_biubiu_23影院","name":"🥒23影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/23影院.json"},
{"key":"csp_biubiu_VIP1280","name":"🥒VIP1280(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/VIP1280.json"},
{"key":"csp_biubiu_小熊影视","name":"🥒小熊影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/小熊影视.json"},
{"key":"csp_biubiu_手机看剧","name":"🥒手机看剧(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/手机看剧.json"},
{"key":"csp_biubiu_创艺影视","name":"🥒创艺影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/创艺影视.json"},
{"key":"csp_biubiu_炫猫影视","name":"🥒炫猫影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/炫猫影视.json"},
{"key":"csp_biubiu_神马影院","name":"🥒神马影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/神马影院.json"},
{"key":"csp_biubiu_哔嘀影视","name":"🥒哔嘀影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/哔嘀影视.json"},
{"key":"csp_biubiu_利丽娅电影","name":"🥒利丽娅电影(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/利丽娅电影.json"},
{"key":"csp_biubiu_奈菲影院","name":"🥒奈菲影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/奈菲影院.json"},
{"key":"csp_biubiu_七年影视","name":"🥒七年影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/七年影视.json"},
{"key":"csp_biubiu_大象TV","name":"🥒大象TV(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/大象TV.json"},
{"key":"csp_biubiu_4kan电影网","name":"🥒4kan电影网(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/4kan电影网.json"},
{"key":"csp_biubiu_蓝莓影视","name":"🥒蓝莓影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/蓝莓影视.json"},
{"key":"csp_biubiu_奇优影院（不支持搜）","name":"🥒奇优影院（不支持搜）(XB)","type":3,"api":"csp_XBiubiu","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/奇优影院（不支持搜）.json"},
{"key":"csp_biubiu_影渣渣","name":"🥒影渣渣(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/影渣渣.json"},
{"key":"csp_biubiu_牛马TV","name":"🥒牛马TV(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/牛马TV.json"},
{"key":"csp_biubiu_飘花播播","name":"🥒飘花播播(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/飘花播播.json"},
{"key":"csp_biubiu_星空影视","name":"🥒星空影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/星空影视.json"},
{"key":"csp_biubiu_豆角网","name":"🥒豆角网(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/豆角网.json"},
{"key":"csp_biubiu_尘落影院","name":"🥒尘落影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/尘落影院.json"},
{"key":"csp_biubiu_city电影","name":"🥒city电影(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/city电影.json"},
{"key":"csp_biubiu_小傻瓜","name":"🥒小傻瓜(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/小傻瓜.json"},
{"key":"csp_biubiu_电影馆","name":"🥒电影馆(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/电影馆.json"},
{"key":"csp_biubiu_爱看影视","name":"🥒爱看影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/爱看影视.json"},
{"key":"csp_biubiu_视中心影院","name":"🥒视中心影院(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/视中心影院.json"},
{"key":"csp_biubiu_老茶馆","name":"🥒老茶馆(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/老茶馆.json"},
{"key":"csp_biubiu_凛冬又至","name":"🥒凛冬又至(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/凛冬又至.json"},
{"key":"csp_biubiu_红领巾","name":"🥒红领巾(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/红领巾.json"},
{"key":"csp_biubiu_老电影","name":"🥒老电影(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/老电影.json"},
{"key":"csp_biubiu_Nike影视网","name":"🥒Nike影视网(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/Nike影视网.json"},
{"key":"csp_biubiu_伊雪湾","name":"🥒伊雪湾(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/伊雪湾.json"},
{"key":"csp_biubiu_极品影视","name":"🥒极品影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/极品影视.json"},
{"key":"csp_biubiu_139影视","name":"🥒139影视(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://gitee.com/dongji2/tt/raw/master/collection/xb/139影视.json"}



],
	"parses": [

		
{"name":"聚合","type":3,"url":"Demo"},
{"name":"并发","type":2,"url":"Parallel"},
{"name":"轮询","type":2,"url":"Sequence"},


{"name":"parwix-MG+","type":0,"url":"https://jx.bozrc.com:4433/player/?url="},
{"name":"OK-QQ","type":0,"url":"https://okjx.cc/?url="},
{"name":"爱豆-MG+","type":0,"url":"https://jx.aidouer.net/?url="},
{"name":"云端1-MG+","type":0,"url":"https://js.52jx.top:2525/?url="},//https://www.302tv.com/?url=
{"name":"云端2-MG+","type":0,"url":"https://www.302tv.com/?url="},//
{"name":"m3u8解析-MG+","type":0,"url":"https://www.302tv.com/?url="},
{"name":"盘古+","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"椰子","type":0,"url":"http://jx.gbxy.net.cn/?url="},
{"name":"老板","type":0,"url":"https://vip.laobandq.com/jiexi.php?url="},
{"name":"醉仙","type":0,"url":"https://jx.zui.cm/?url="},
{"name":"北雁","type":0,"url":"https://jx.beiyan.cc:4433/?url="},

{"name":"parwix1","type":0,"url":"https://jx.parwix.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"parwix2","type":0,"url":"https://jx.parwix.com:4433/player/analysis.php?v=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},


{"name":"乐多","type":1,"url":"https://api.ldjx.cc/wp-api/getvodurl.php?token=1001&vid="},
{"name":"钢铁侠","type":1,"url":"https://json.freejx.in/?url="},
{"name": "GGTV自用","type": 1,"url": "https://play.fuqizhishi.com/jx/API.php?appkey=xiaobaiiiii&url="},
{"name":"江湖","type":1,"url":"http://211.99.99.236:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","iqiyi","奇艺","爱奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果","xigua","西瓜","sohu","搜狐","cntv","cctv","央视","1905","m1905"]}},

{"name":"ck","type":1,"url":"http://api.ckflv.cn/?url="},
{"name":"keyu","type":1,"url":"http://newjiexi.gotka.top/keyu3.php?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name": "GGTV高清","type": 1,"url": "https://play.fuqizhishi.com/jx/API.php?appkey=xiaobai888&url="},
{"name":"GGTV自用","type":1,"url":"https://play.fuqizhishi.com/jx/API.php?appkey=ixiaobai&url="},
{"name": "瓜皮","type": 0,"url": "https://jxpl.lihaoyun.top/?url="},
{"name": "江湖","type": 1,"url": "http://211.99.99.236:4567/jhjson/ceshi.php?url="},
{"name": "无名(2)","type": 1,"url": "https://vip.byteamone.cn/api/?key=bbpSbJMpjxLqcBKzUW&url="},
{"name": "Fosi嗅探","type": 0,"url": "https://play.fositv.com/?url="},
{"name": "蓝豆嗅探","type": 0,"url": "http://124.248.66.26:4545/QXQP/?url="},
{"name": "codjx","type": 0,"url": "https://www.codjx.com/?url="},
{"name":"解析5","type":1,"url":"https://play.fuqizhishi.com/jx/API.php?appkey=xiaobaiiiii&url="},
{"name":"GGTV自用","type":1,"url":"https://play.fuqizhishi.com/jx/API.php?appkey=xiaobaiiiii&url="},


{"name":"纯净","type":0,"url":"https://z1.m1907.cn/?jx="},
{"name":"诺讯","type":0,"url":"https://www.nxflv.com/?url="},
{"name":"诺讯1","type":0,"url":"https://yun.nxflv.com/?url="},
{"name":"BL","type":0,"url":"https://vip.bljiex.com/?v="},
{"name":"CK","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name":"H8","type":0,"url":"https://www.h8jx.com/jiexi.php?url="},
{"name":"解析","type":0,"url":"https://ckmov.ccyjjd.com/ckmov/?url="},
{"name":"解析la","type":0,"url":"https://api.jiexi.la/?url="},

{"name":"PM","type":0,"url":"https://www.playm3u8.cn/jiexi.php?url="},
{"name":"盘古","type":0,"url":"https://www.pangujiexi.cc/jiexi.php?url="},
{"name":"全民","type":0,"url":"https://jx.blbo.cc:4433/?url="},
{"name":"七哥","type":0,"url":"https://jx.mmkv.cn/tv.php?url="},
{"name":"RDHK","type":0,"url":"https://jx.rdhk.net/?v="},
{"name":"人人迷","type":0,"url":"https://jx.blbo.cc:4433/?url="},
{"name":"思古3","type":0,"url":"https://jsap.attakids.com/?url="},
{"name":"云端1","type":0,"url":"https://sb.5gseo.net/?url="},
{"name":"云析","type":0,"url":"https://jx.yparse.com/index.php?url="},
{"name":"180","type":0,"url":"https://jx.000180.top/jx/?url="},
{"name":"8090","type":0,"url":"https://www.8090g.cn/?url="}
	
	],
	
	
"flags":["youku","qq","iqiyi","imgo","xueren","m1905","qiyi","letv","sohu","tudou","pptv","dbm3u8","mgtv","wasu","bilibili","le","duoduozy","renrenmi","xigua","优酷","西瓜","乐视","芒果","腾讯","爱奇艺","奇艺","ltnb","rx","CL4K","xfyun","wuduzy","哔哩哔哩","哔哩"],"ijk":[{"group":"软解码","options":[{"category":4,"name":"opensles","value":"0"},{"category":4,"name":"overlay-format","value":"842225234"},{"category":4,"name":"framedrop","value":"1"},{"category":4,"name":"soundtouch","value":"1"},{"category":4,"name":"start-on-prepared","value":"1"},{"category":1,"name":"http-detect-range-support","value":"0"},{"category":1,"name":"fflags","value":"fastseek"},{"category":2,"name":"skip_loop_filter","value":"48"},{"category":4,"name":"reconnect","value":"1"},{"category":4,"name":"enable-accurate-seek","value":"0"},{"category":4,"name":"mediacodec","value":"0"},{"category":4,"name":"mediacodec-auto-rotate","value":"0"},{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"},{"category":4,"name":"mediacodec-hevc","value":"0"},{"category":1,"name":"dns_cache_timeout","value":"600000000"}]},{"group":"硬解码","options":[{"category":4,"name":"opensles","value":"0"},{"category":4,"name":"overlay-format","value":"842225234"},{"category":4,"name":"framedrop","value":"1"},{"category":4,"name":"soundtouch","value":"1"},{"category":4,"name":"start-on-prepared","value":"1"},{"category":1,"name":"http-detect-range-support","value":"0"},{"category":1,"name":"fflags","value":"fastseek"},{"category":2,"name":"skip_loop_filter","value":"48"},{"category":4,"name":"reconnect","value":"1"},{"category":4,"name":"enable-accurate-seek","value":"0"},{"category":4,"name":"mediacodec","value":"1"},{"category":4,"name":"mediacodec-auto-rotate","value":"1"},{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"},{"category":4,"name":"mediacodec-hevc","value":"1"},{"category":1,"name":"dns_cache_timeout","value":"600000000"}]}],"ads":["lf1-cdn-tos.bytegoofy.com","mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"]}
